[colors.primary]
background = "#1e1e2e"
foreground = "#bac2de"

[colors.cursor]
text = "#1e1e2e"
cursor = "#bac2de"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#bac2de"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#bac2de"

[colors.search.focused_match]
foreground = "CellBackground"
background = "CellForeground"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#45475a"
background = "#bac2de"

[colors.selection]
text = "CellBackground"
background = "CellForeground"

[colors.normal]
black = "#1e1e2e"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#c49bf6"
cyan = "#94e2d5"
white = "#cdd6f4"

[colors.bright]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.dim]
black = "#bac2de"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#cba6f7"
cyan = "#94e2d5"
white = "#45475a"
